/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AView;
import AModel.User;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Jaydon
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
  public MenuView(){
      initComponents();
      this.setVisible(true);
  
  }
    
   public MenuView(User user){
       initComponents();
       initPanelComponents(user);
       if (user.getPosition()==User.Position.PRODUCT_MANAGER){
           this.setTitle("Product Manager Menu");
           this.setNaviBar(user.getPosition());
           this.setVisible(true);
       }
       else if (user.getPosition() == User.Position.ADMIN){
           this.setTitle("Admin Menu");
           this.setNaviBar(user.getPosition());
           this.setVisible(true);
       
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JLayeredPane();
        menuAdmin = new javax.swing.JPanel();
        naviBarAdmin = new javax.swing.JPanel();
        profileButtonAD = new javax.swing.JButton();
        managerButtonAD = new javax.swing.JButton();
        supplierButtonAD = new javax.swing.JButton();
        productButtonAD = new javax.swing.JButton();
        logButtonAD = new javax.swing.JButton();
        dashboardButtonAD = new javax.swing.JButton();
        logOutAD = new javax.swing.JButton();
        contentHolderAdmin = new javax.swing.JLayeredPane();
        profilePanelAD = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        userTextArea = new javax.swing.JTextArea();
        emailText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        userText = new javax.swing.JTextField();
        contactText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        managerPanelAD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        supplierPanelAD = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logPanelAD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dashboardPanelAD = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        productPanelAD = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menuPM = new javax.swing.JPanel();
        naviBarPM = new javax.swing.JPanel();
        profileButtonPM = new javax.swing.JButton();
        catalogueButtonPM = new javax.swing.JButton();
        productButtonPM = new javax.swing.JButton();
        logOutPM = new javax.swing.JButton();
        dashboardButtonPM = new javax.swing.JButton();
        contentHolderPM = new javax.swing.JLayeredPane();
        dashboardPanelPM = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cataloguePanelPM = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        productPanelPM = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        profilePanelPM = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        basePanel.setBackground(new java.awt.Color(204, 204, 204));
        basePanel.setAutoscrolls(true);
        basePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        basePanel.setLayout(new java.awt.CardLayout());

        menuAdmin.setBackground(new java.awt.Color(102, 102, 102));

        naviBarAdmin.setPreferredSize(new java.awt.Dimension(143, 522));

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        profileButtonAD.setText("Manage Personal Profile");
        profileButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        managerButtonAD.setText("Manage Manager");
        managerButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        supplierButtonAD.setText("Manage Supplier");
        supplierButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        productButtonAD.setText("Manage Product");
        productButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        logButtonAD.setText("Inspect Log");
        logButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        dashboardButtonAD.setText("Design Dashboard");
        dashboardButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonADActionPerformed(evt);
            }
        });

        logOutAD.setText("Log Out");

        javax.swing.GroupLayout naviBarAdminLayout = new javax.swing.GroupLayout(naviBarAdmin);
        naviBarAdmin.setLayout(naviBarAdminLayout);
        naviBarAdminLayout.setHorizontalGroup(
            naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, naviBarAdminLayout.createSequentialGroup()
                .addGroup(naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(managerButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(profileButtonAD, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logOutAD, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        naviBarAdminLayout.setVerticalGroup(
            naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(managerButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutAD)
                .addGap(23, 23, 23))
        );

        contentHolderAdmin.setLayout(new java.awt.CardLayout());

        profilePanelAD.setBackground(new java.awt.Color(250, 246, 203));

        Title.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 51));
        Title.setText("Manage Personal Profile");

        userTextArea.setBackground(new java.awt.Color(52, 73, 85));
        userTextArea.setColumns(20);
        userTextArea.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        userTextArea.setForeground(new java.awt.Color(255, 255, 255));
        userTextArea.setRows(5);
        userTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Name: ");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Email: ");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Contact: ");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Username: ");

        jButton1.setText("Update");

        jButton2.setText("Cancel");

        javax.swing.GroupLayout profilePanelADLayout = new javax.swing.GroupLayout(profilePanelAD);
        profilePanelAD.setLayout(profilePanelADLayout);
        profilePanelADLayout.setHorizontalGroup(
            profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelADLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelADLayout.createSequentialGroup()
                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profilePanelADLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelADLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profilePanelADLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(profilePanelADLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelADLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelADLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(69, 69, 69)
                                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(profilePanelADLayout.createSequentialGroup()
                                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(71, 71, 71)
                                .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(121, 121, 121)
                .addComponent(userTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        profilePanelADLayout.setVerticalGroup(
            profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelADLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(profilePanelADLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(41, 41, 41)
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(108, 108, 108)
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(143, 143, 143))
        );

        contentHolderAdmin.add(profilePanelAD, "card8");

        jLabel1.setText("Manager");

        javax.swing.GroupLayout managerPanelADLayout = new javax.swing.GroupLayout(managerPanelAD);
        managerPanelAD.setLayout(managerPanelADLayout);
        managerPanelADLayout.setHorizontalGroup(
            managerPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerPanelADLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(626, Short.MAX_VALUE))
        );
        managerPanelADLayout.setVerticalGroup(
            managerPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerPanelADLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(managerPanelAD, "card4");

        jLabel5.setText("Supplier");

        javax.swing.GroupLayout supplierPanelADLayout = new javax.swing.GroupLayout(supplierPanelAD);
        supplierPanelAD.setLayout(supplierPanelADLayout);
        supplierPanelADLayout.setHorizontalGroup(
            supplierPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelADLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel5)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        supplierPanelADLayout.setVerticalGroup(
            supplierPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelADLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel5)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(supplierPanelAD, "card2");

        jLabel6.setText("Log");

        javax.swing.GroupLayout logPanelADLayout = new javax.swing.GroupLayout(logPanelAD);
        logPanelAD.setLayout(logPanelADLayout);
        logPanelADLayout.setHorizontalGroup(
            logPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelADLayout.createSequentialGroup()
                .addContainerGap(612, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(306, 306, 306))
        );
        logPanelADLayout.setVerticalGroup(
            logPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelADLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel6)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(logPanelAD, "card3");

        jLabel4.setText("dashboard");

        javax.swing.GroupLayout dashboardPanelADLayout = new javax.swing.GroupLayout(dashboardPanelAD);
        dashboardPanelAD.setLayout(dashboardPanelADLayout);
        dashboardPanelADLayout.setHorizontalGroup(
            dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
            .addGroup(dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardPanelADLayout.createSequentialGroup()
                    .addGap(340, 340, 340)
                    .addComponent(jLabel4)
                    .addContainerGap(538, Short.MAX_VALUE)))
        );
        dashboardPanelADLayout.setVerticalGroup(
            dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardPanelADLayout.createSequentialGroup()
                    .addGap(262, 262, 262)
                    .addComponent(jLabel4)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        contentHolderAdmin.add(dashboardPanelAD, "card5");

        jLabel7.setText("product");

        javax.swing.GroupLayout productPanelADLayout = new javax.swing.GroupLayout(productPanelAD);
        productPanelAD.setLayout(productPanelADLayout);
        productPanelADLayout.setHorizontalGroup(
            productPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelADLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel7)
                .addContainerGap(620, Short.MAX_VALUE))
        );
        productPanelADLayout.setVerticalGroup(
            productPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelADLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel7)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(productPanelAD, "card9");

        javax.swing.GroupLayout menuAdminLayout = new javax.swing.GroupLayout(menuAdmin);
        menuAdmin.setLayout(menuAdminLayout);
        menuAdminLayout.setHorizontalGroup(
            menuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAdminLayout.createSequentialGroup()
                .addComponent(naviBarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentHolderAdmin))
        );
        menuAdminLayout.setVerticalGroup(
            menuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naviBarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addComponent(contentHolderAdmin)
        );

        basePanel.add(menuAdmin, "card3");

        menuPM.setBackground(new java.awt.Color(153, 153, 153));

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        profileButtonPM.setText("Manage Personal Profile");
        profileButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonPMActionPerformed(evt);
            }
        });

        catalogueButtonPM.setText("Manage Product Catalogue");
        catalogueButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogueButtonPMActionPerformed(evt);
            }
        });

        productButtonPM.setText("Manage Product Information");
        productButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonPMActionPerformed(evt);
            }
        });

        logOutPM.setText("Log Out");

        dashboardButtonPM.setText("Design Summary Dashboard");
        dashboardButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout naviBarPMLayout = new javax.swing.GroupLayout(naviBarPM);
        naviBarPM.setLayout(naviBarPMLayout);
        naviBarPMLayout.setHorizontalGroup(
            naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarPMLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(catalogueButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardButtonPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        naviBarPMLayout.setVerticalGroup(
            naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarPMLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(profileButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(productButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(catalogueButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutPM)
                .addGap(20, 20, 20))
        );

        contentHolderPM.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout dashboardPanelPMLayout = new javax.swing.GroupLayout(dashboardPanelPM);
        dashboardPanelPM.setLayout(dashboardPanelPMLayout);
        dashboardPanelPMLayout.setHorizontalGroup(
            dashboardPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelPMLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel2)
                .addContainerGap(630, Short.MAX_VALUE))
        );
        dashboardPanelPMLayout.setVerticalGroup(
            dashboardPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelPMLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel2)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        contentHolderPM.add(dashboardPanelPM, "card5");

        jLabel3.setText("Catalogue");

        javax.swing.GroupLayout cataloguePanelPMLayout = new javax.swing.GroupLayout(cataloguePanelPM);
        cataloguePanelPM.setLayout(cataloguePanelPMLayout);
        cataloguePanelPMLayout.setHorizontalGroup(
            cataloguePanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cataloguePanelPMLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel3)
                .addContainerGap(646, Short.MAX_VALUE))
        );
        cataloguePanelPMLayout.setVerticalGroup(
            cataloguePanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cataloguePanelPMLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel3)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        contentHolderPM.add(cataloguePanelPM, "card4");

        jLabel9.setText("Product");

        javax.swing.GroupLayout productPanelPMLayout = new javax.swing.GroupLayout(productPanelPM);
        productPanelPM.setLayout(productPanelPMLayout);
        productPanelPMLayout.setHorizontalGroup(
            productPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelPMLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel9)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        productPanelPMLayout.setVerticalGroup(
            productPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelPMLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel9)
                .addContainerGap(490, Short.MAX_VALUE))
        );

        contentHolderPM.add(productPanelPM, "card3");

        jLabel10.setText("Profile");

        javax.swing.GroupLayout profilePanelPMLayout = new javax.swing.GroupLayout(profilePanelPM);
        profilePanelPM.setLayout(profilePanelPMLayout);
        profilePanelPMLayout.setHorizontalGroup(
            profilePanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelPMLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel10)
                .addContainerGap(646, Short.MAX_VALUE))
        );
        profilePanelPMLayout.setVerticalGroup(
            profilePanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelPMLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel10)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        contentHolderPM.add(profilePanelPM, "card2");

        javax.swing.GroupLayout menuPMLayout = new javax.swing.GroupLayout(menuPM);
        menuPM.setLayout(menuPMLayout);
        menuPMLayout.setHorizontalGroup(
            menuPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPMLayout.createSequentialGroup()
                .addComponent(naviBarPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentHolderPM))
        );
        menuPMLayout.setVerticalGroup(
            menuPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naviBarPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentHolderPM)
        );

        basePanel.add(menuPM, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initPanelComponents(User user){
        /**
         * Manage Personal Profile ADMIN
         */
        String profileInfo = "Name: \t"+user.getName() +"\n"+"Email: \t"+user.getEmail() +"\n"+"Contact: \t"+user.getContact() +"\n"+
                "Position: \t"+user.getPosition() +"\n"
                 +"Gender: \t" +user.getGender()+"\n"+ "Username: \t" + user.getLogin();
        this.userTextArea.setText(profileInfo);
        this.nameText.setText(user.getName());
        this.contactText.setText(user.getContact());
        this.emailText.setText(user.getEmail());
        this.userText.setText(user.getLogin().toString());
   
    }
    
    
    /**
     * Navigation Bar Switching
     * @param evt 
     */
    // <editor-fold defaultstate="collapsed" desc="Panel Switching">
    private void profileButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonADActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderAdmin,profilePanelAD );
    }//GEN-LAST:event_profileButtonADActionPerformed

    private void managerButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButtonADActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderAdmin,managerPanelAD);
    }//GEN-LAST:event_managerButtonADActionPerformed

    private void supplierButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonADActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderAdmin,supplierPanelAD);
    }//GEN-LAST:event_supplierButtonADActionPerformed

    private void productButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonADActionPerformed
         this.switchContentPanels(contentHolderAdmin,productPanelAD);
    }//GEN-LAST:event_productButtonADActionPerformed

    private void logButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonADActionPerformed
        // TODO add your handling code here:
         this.switchContentPanels(contentHolderAdmin,logPanelAD);
    
    }//GEN-LAST:event_logButtonADActionPerformed

    private void dashboardButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonADActionPerformed
        // TODO add your handling code here:
         this.switchContentPanels(contentHolderAdmin,dashboardPanelAD);
    }//GEN-LAST:event_dashboardButtonADActionPerformed

    private void profileButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonPMActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderPM, profilePanelPM);
    }//GEN-LAST:event_profileButtonPMActionPerformed

    private void productButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonPMActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderPM, productPanelPM);
    }//GEN-LAST:event_productButtonPMActionPerformed

    private void catalogueButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogueButtonPMActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderPM, cataloguePanelPM);
    }//GEN-LAST:event_catalogueButtonPMActionPerformed

    private void dashboardButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonPMActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderPM, dashboardPanelPM);
    }//GEN-LAST:event_dashboardButtonPMActionPerformed
//</editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    /*
    * Menu Set up
    */
    
    
    public void setNaviBar(User.Position p) {
        basePanel.removeAll();
        switch(p){
            case ADMIN:
                basePanel.removeAll();
                basePanel.add(menuAdmin);
                basePanel.repaint();
                basePanel.revalidate();
                break;
                
            case PRODUCT_MANAGER:
                basePanel.removeAll();
                basePanel.add(menuPM);
                basePanel.repaint();
                basePanel.revalidate();
                break;
        }
    
    }
    
    
  
    /**
     * Panel Switching
     */    

    public void switchContentPanels(JLayeredPane holder, JPanel content ){
        holder.removeAll();
        holder.add(content);
        holder.repaint();
        holder.revalidate();
    }

  
    
   /**
    * Getter and Setter
    */ 
    
 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLayeredPane basePanel;
    private javax.swing.JButton catalogueButtonPM;
    private javax.swing.JPanel cataloguePanelPM;
    private javax.swing.JTextField contactText;
    private javax.swing.JLayeredPane contentHolderAdmin;
    private javax.swing.JLayeredPane contentHolderPM;
    private javax.swing.JButton dashboardButtonAD;
    private javax.swing.JButton dashboardButtonPM;
    private javax.swing.JPanel dashboardPanelAD;
    private javax.swing.JPanel dashboardPanelPM;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logButtonAD;
    private javax.swing.JButton logOutAD;
    private javax.swing.JButton logOutPM;
    private javax.swing.JPanel logPanelAD;
    private javax.swing.JButton managerButtonAD;
    private javax.swing.JPanel managerPanelAD;
    private javax.swing.JPanel menuAdmin;
    private javax.swing.JPanel menuPM;
    private javax.swing.JTextField nameText;
    private javax.swing.JPanel naviBarAdmin;
    private javax.swing.JPanel naviBarPM;
    private javax.swing.JButton productButtonAD;
    private javax.swing.JButton productButtonPM;
    private javax.swing.JPanel productPanelAD;
    private javax.swing.JPanel productPanelPM;
    private javax.swing.JButton profileButtonAD;
    private javax.swing.JButton profileButtonPM;
    private javax.swing.JPanel profilePanelAD;
    private javax.swing.JPanel profilePanelPM;
    private javax.swing.JButton supplierButtonAD;
    private javax.swing.JPanel supplierPanelAD;
    private javax.swing.JTextField userText;
    private javax.swing.JTextArea userTextArea;
    // End of variables declaration//GEN-END:variables


}
