/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AView;
import AModel.User;
import javax.swing.*;

/**
 *
 * @author Jaydon
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuView() {
        initComponents();
        this.setTitle("Main Menu");
        this.setVisible(true);
        
    }
    
   public MenuView(User.Position p){
       initComponents();
       if (p == User.Position.PRODUCT_MANAGER){
           this.setTitle("Product Manager Menu");
           this.setNaviBar(p);
           this.setVisible(true);
       }
       else if (p == User.Position.ADMIN){
           this.setTitle("Admin Menu");
           this.setNaviBar(p);
           this.setVisible(true);
       
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JLayeredPane();
        menuAdmin = new javax.swing.JPanel();
        naviBarAdmin = new javax.swing.JPanel();
        profileButtonAD = new javax.swing.JButton();
        managerButtonAD = new javax.swing.JButton();
        supplierButtonAD = new javax.swing.JButton();
        productButtonAD = new javax.swing.JButton();
        logButtonAD = new javax.swing.JButton();
        dashboardButtonAD = new javax.swing.JButton();
        logOutAD = new javax.swing.JButton();
        contentHolderAdmin = new javax.swing.JLayeredPane();
        supplierPanel = new javax.swing.JPanel();
        logPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        managerPanel = new javax.swing.JPanel();
        dashboardPanelAD = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        menuPM = new javax.swing.JPanel();
        naviBarPM = new javax.swing.JPanel();
        profileButtonPM = new javax.swing.JButton();
        catalogueButtonPM = new javax.swing.JButton();
        productButtonPM = new javax.swing.JButton();
        logOutPM = new javax.swing.JButton();
        dashboardButtonPM = new javax.swing.JButton();
        contentHolderPM = new javax.swing.JLayeredPane();
        dashboardPanelPM = new javax.swing.JPanel();
        cataloguePanel = new javax.swing.JPanel();
        productPanel = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        basePanel.setBackground(new java.awt.Color(204, 204, 204));
        basePanel.setLayout(new java.awt.CardLayout());

        menuAdmin.setBackground(new java.awt.Color(102, 102, 102));

        naviBarAdmin.setPreferredSize(new java.awt.Dimension(143, 522));

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        profileButtonAD.setText("Manage Personal Profile");

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        managerButtonAD.setText("Manage Manager");

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        supplierButtonAD.setText("Manage Supplier");

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        productButtonAD.setText("Manage Product");

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        logButtonAD.setText("Inspect Log");

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        dashboardButtonAD.setText("Design Dashboard");

        logOutAD.setText("Log Out");

        javax.swing.GroupLayout naviBarAdminLayout = new javax.swing.GroupLayout(naviBarAdmin);
        naviBarAdmin.setLayout(naviBarAdminLayout);
        naviBarAdminLayout.setHorizontalGroup(
            naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, naviBarAdminLayout.createSequentialGroup()
                .addGroup(naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(managerButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(profileButtonAD, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logOutAD, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        naviBarAdminLayout.setVerticalGroup(
            naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(managerButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutAD)
                .addGap(23, 23, 23))
        );

        contentHolderAdmin.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout supplierPanelLayout = new javax.swing.GroupLayout(supplierPanel);
        supplierPanel.setLayout(supplierPanelLayout);
        supplierPanelLayout.setHorizontalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        supplierPanelLayout.setVerticalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        contentHolderAdmin.add(supplierPanel, "card2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        contentHolderAdmin.add(logPanel, "card3");

        javax.swing.GroupLayout managerPanelLayout = new javax.swing.GroupLayout(managerPanel);
        managerPanel.setLayout(managerPanelLayout);
        managerPanelLayout.setHorizontalGroup(
            managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        managerPanelLayout.setVerticalGroup(
            managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        contentHolderAdmin.add(managerPanel, "card4");

        javax.swing.GroupLayout dashboardPanelADLayout = new javax.swing.GroupLayout(dashboardPanelAD);
        dashboardPanelAD.setLayout(dashboardPanelADLayout);
        dashboardPanelADLayout.setHorizontalGroup(
            dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        dashboardPanelADLayout.setVerticalGroup(
            dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        contentHolderAdmin.add(dashboardPanelAD, "card5");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        contentHolderAdmin.add(jPanel6, "card6");

        javax.swing.GroupLayout menuAdminLayout = new javax.swing.GroupLayout(menuAdmin);
        menuAdmin.setLayout(menuAdminLayout);
        menuAdminLayout.setHorizontalGroup(
            menuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAdminLayout.createSequentialGroup()
                .addComponent(naviBarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentHolderAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(724, Short.MAX_VALUE))
        );
        menuAdminLayout.setVerticalGroup(
            menuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naviBarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addComponent(contentHolderAdmin)
        );

        basePanel.add(menuAdmin, "card3");

        menuPM.setBackground(new java.awt.Color(153, 153, 153));

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        profileButtonPM.setText("Manage Personal Profile");

        catalogueButtonPM.setText("Manage Product Catalogue");

        productButtonPM.setText("Manage Product Information");

        logOutPM.setText("Log Out");

        dashboardButtonPM.setText("Design Summary Dashboard");

        javax.swing.GroupLayout naviBarPMLayout = new javax.swing.GroupLayout(naviBarPM);
        naviBarPM.setLayout(naviBarPMLayout);
        naviBarPMLayout.setHorizontalGroup(
            naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarPMLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(catalogueButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardButtonPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        naviBarPMLayout.setVerticalGroup(
            naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarPMLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(profileButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(productButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(catalogueButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutPM)
                .addGap(20, 20, 20))
        );

        contentHolderPM.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout dashboardPanelPMLayout = new javax.swing.GroupLayout(dashboardPanelPM);
        dashboardPanelPM.setLayout(dashboardPanelPMLayout);
        dashboardPanelPMLayout.setHorizontalGroup(
            dashboardPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        dashboardPanelPMLayout.setVerticalGroup(
            dashboardPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        contentHolderPM.add(dashboardPanelPM, "card5");

        javax.swing.GroupLayout cataloguePanelLayout = new javax.swing.GroupLayout(cataloguePanel);
        cataloguePanel.setLayout(cataloguePanelLayout);
        cataloguePanelLayout.setHorizontalGroup(
            cataloguePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        cataloguePanelLayout.setVerticalGroup(
            cataloguePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        contentHolderPM.add(cataloguePanel, "card4");

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        contentHolderPM.add(productPanel, "card3");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        contentHolderPM.add(profilePanel, "card2");

        javax.swing.GroupLayout menuPMLayout = new javax.swing.GroupLayout(menuPM);
        menuPM.setLayout(menuPMLayout);
        menuPMLayout.setHorizontalGroup(
            menuPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPMLayout.createSequentialGroup()
                .addComponent(naviBarPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentHolderPM))
        );
        menuPMLayout.setVerticalGroup(
            menuPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naviBarPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentHolderPM)
        );

        basePanel.add(menuPM, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    /*
    * Menu Set up
    */
    
    
    public void setNaviBar(User.Position p) {
        basePanel.removeAll();
        switch(p){
            case ADMIN:
                basePanel.removeAll();
                basePanel.add(menuAdmin);
                basePanel.repaint();
                basePanel.revalidate();
                break;
                
            case PRODUCT_MANAGER:
                basePanel.removeAll();
                basePanel.add(menuPM);
                basePanel.repaint();
                basePanel.revalidate();
                break;
        }
    
    }
    
    
    
    
    /**
     * Panel Switching
     */    

    public void switchContentPanels(JPanel panel){
        basePanel.removeAll();
        basePanel.add(panel);
        basePanel.repaint();
        basePanel.revalidate();
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane basePanel;
    private javax.swing.JButton catalogueButtonPM;
    private javax.swing.JPanel cataloguePanel;
    private javax.swing.JLayeredPane contentHolderAdmin;
    private javax.swing.JLayeredPane contentHolderPM;
    private javax.swing.JButton dashboardButtonAD;
    private javax.swing.JButton dashboardButtonPM;
    private javax.swing.JPanel dashboardPanelAD;
    private javax.swing.JPanel dashboardPanelPM;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton logButtonAD;
    private javax.swing.JButton logOutAD;
    private javax.swing.JButton logOutPM;
    private javax.swing.JPanel logPanel;
    private javax.swing.JButton managerButtonAD;
    private javax.swing.JPanel managerPanel;
    private javax.swing.JPanel menuAdmin;
    private javax.swing.JPanel menuPM;
    private javax.swing.JPanel naviBarAdmin;
    private javax.swing.JPanel naviBarPM;
    private javax.swing.JButton productButtonAD;
    private javax.swing.JButton productButtonPM;
    private javax.swing.JPanel productPanel;
    private javax.swing.JButton profileButtonAD;
    private javax.swing.JButton profileButtonPM;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton supplierButtonAD;
    private javax.swing.JPanel supplierPanel;
    // End of variables declaration//GEN-END:variables
}
