/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AView;
import AModel.DatabaseManager;
import AModel.*;
import AModel.TableList;
import AModel.User;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaydon
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Properties Model
     */
    MenuModel model;
    
    /**
     * Creates new form Menu
     */
    // <editor-fold defaultstate="collapsed" desc="Constructor">  

    
   public MenuView(MenuModel model){
       this.model =model;
       initComponents();
       initPanelComponents(model.user,model.DB);
       if (model.user.getPosition()==User.Position.PRODUCT_MANAGER){
           this.setTitle("Product Manager Menu");
           this.setNaviBar(model.user.getPosition());
           this.setVisible(true);
       }
       else if (model.user.getPosition() == User.Position.ADMIN){
           this.setTitle("Admin Menu");
           this.setNaviBar(model.user.getPosition());
           this.setVisible(true);
       }
   }
   //</editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JLayeredPane();
        menuAdmin = new javax.swing.JPanel();
        naviBarAdmin = new javax.swing.JPanel();
        profileButtonAD = new javax.swing.JButton();
        managerButtonAD = new javax.swing.JButton();
        supplierButtonAD = new javax.swing.JButton();
        productButtonAD = new javax.swing.JButton();
        logButtonAD = new javax.swing.JButton();
        dashboardButtonAD = new javax.swing.JButton();
        logOutAD = new javax.swing.JButton();
        contentHolderAdmin = new javax.swing.JLayeredPane();
        managerPanelAD = new javax.swing.JPanel();
        createUserButton = new javax.swing.JButton();
        viewUserButton = new javax.swing.JButton();
        userSubPanel = new javax.swing.JLayeredPane();
        createPM = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        newEmail = new javax.swing.JTextField();
        newContact = new javax.swing.JTextField();
        newUsername = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        newPass1 = new javax.swing.JPasswordField();
        newPass2 = new javax.swing.JPasswordField();
        NewUserTitle = new javax.swing.JLabel();
        enterButton1 = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        viewPM = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        supplierPanelAD = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logPanelAD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        dashboardPanelAD = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        productPanelAD = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        profilePanelAD = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        userTextArea = new javax.swing.JTextArea();
        emailText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        userText = new javax.swing.JTextField();
        contactText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menuPM = new javax.swing.JPanel();
        naviBarPM = new javax.swing.JPanel();
        profileButtonPM = new javax.swing.JButton();
        catalogueButtonPM = new javax.swing.JButton();
        productButtonPM = new javax.swing.JButton();
        logOutPM = new javax.swing.JButton();
        dashboardButtonPM = new javax.swing.JButton();
        contentHolderPM = new javax.swing.JLayeredPane();
        dashboardPanelPM = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cataloguePanelPM = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        productPanelPM = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        profilePanelPM = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setSize(new java.awt.Dimension(350, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        basePanel.setBackground(new java.awt.Color(204, 204, 204));
        basePanel.setAutoscrolls(true);
        basePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        basePanel.setLayout(new java.awt.CardLayout());

        menuAdmin.setBackground(new java.awt.Color(102, 102, 102));

        naviBarAdmin.setAlignmentX(0.0F);
        naviBarAdmin.setPreferredSize(new java.awt.Dimension(143, 522));

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        profileButtonAD.setText("Manage Personal Profile");
        profileButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        managerButtonAD.setText("Manage Manager");
        managerButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        supplierButtonAD.setText("Manage Supplier");
        supplierButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        productButtonAD.setText("Manage Product");
        productButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        logButtonAD.setText("Inspect Log");
        logButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonADActionPerformed(evt);
            }
        });

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        dashboardButtonAD.setText("Design Dashboard");
        dashboardButtonAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonADActionPerformed(evt);
            }
        });

        logOutAD.setText("Log Out");

        javax.swing.GroupLayout naviBarAdminLayout = new javax.swing.GroupLayout(naviBarAdmin);
        naviBarAdmin.setLayout(naviBarAdminLayout);
        naviBarAdminLayout.setHorizontalGroup(
            naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, naviBarAdminLayout.createSequentialGroup()
                .addGroup(naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(managerButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(profileButtonAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(naviBarAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logOutAD, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        naviBarAdminLayout.setVerticalGroup(
            naviBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarAdminLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(profileButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(managerButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardButtonAD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutAD)
                .addGap(32, 32, 32))
        );

        contentHolderAdmin.setLayout(new java.awt.CardLayout());

        managerPanelAD.setBackground(new java.awt.Color(204, 204, 204));
        managerPanelAD.setForeground(new java.awt.Color(0, 0, 0));

        createUserButton.setText("Create User");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        viewUserButton.setText("viewUser");
        viewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserButtonActionPerformed(evt);
            }
        });

        userSubPanel.setBackground(new java.awt.Color(153, 153, 153));
        userSubPanel.setLayout(new java.awt.CardLayout());

        createPM.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Contact:");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Email");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Username");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Password");

        newName.setText("John Smith");

        newEmail.setText("JohnSmith@tgmail.com");

        newContact.setText("016-123 4567");

        newUsername.setText("JohnSmith");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Confirm Password");

        newPass1.setText("password");

        newPass2.setText("password");

        NewUserTitle.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        NewUserTitle.setForeground(new java.awt.Color(0, 0, 0));
        NewUserTitle.setText("Create A New User");

        enterButton1.setText("Enter");
        enterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButton1ActionPerformed(evt);
            }
        });

        cancelButton1.setText("Cancel");

        warningLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout createPMLayout = new javax.swing.GroupLayout(createPM);
        createPM.setLayout(createPMLayout);
        createPMLayout.setHorizontalGroup(
            createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPMLayout.createSequentialGroup()
                .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPMLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(NewUserTitle))
                    .addGroup(createPMLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1)
                            .addComponent(jLabel17))
                        .addGap(37, 37, 37)
                        .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newContact, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(newPass1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warningLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 253, Short.MAX_VALUE))
        );
        createPMLayout.setVerticalGroup(
            createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPMLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(NewUserTitle)
                .addGap(69, 69, 69)
                .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(newContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(newPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(createPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(newPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        userSubPanel.add(createPM, "card2");

        viewPM.setBackground(new java.awt.Color(153, 153, 153));
        viewPM.setFocusable(false);

        userTable.setAutoCreateRowSorter(true);
        userTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setAutoscrolls(false);
        jScrollPane1.setViewportView(userTable);

        javax.swing.GroupLayout viewPMLayout = new javax.swing.GroupLayout(viewPM);
        viewPM.setLayout(viewPMLayout);
        viewPMLayout.setHorizontalGroup(
            viewPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPMLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        viewPMLayout.setVerticalGroup(
            viewPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPMLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        userSubPanel.add(viewPM, "card2");

        javax.swing.GroupLayout managerPanelADLayout = new javax.swing.GroupLayout(managerPanelAD);
        managerPanelAD.setLayout(managerPanelADLayout);
        managerPanelADLayout.setHorizontalGroup(
            managerPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerPanelADLayout.createSequentialGroup()
                .addGroup(managerPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerPanelADLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerPanelADLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userSubPanel))
        );
        managerPanelADLayout.setVerticalGroup(
            managerPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userSubPanel)
            .addGroup(managerPanelADLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(createUserButton)
                .addGap(254, 254, 254)
                .addComponent(viewUserButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(managerPanelAD, "card4");

        jLabel5.setText("Supplier");

        javax.swing.GroupLayout supplierPanelADLayout = new javax.swing.GroupLayout(supplierPanelAD);
        supplierPanelAD.setLayout(supplierPanelADLayout);
        supplierPanelADLayout.setHorizontalGroup(
            supplierPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelADLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel5)
                .addContainerGap(571, Short.MAX_VALUE))
        );
        supplierPanelADLayout.setVerticalGroup(
            supplierPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelADLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel5)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(supplierPanelAD, "card2");

        logPanelAD.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("System Log");

        logTable.setAutoCreateRowSorter(true);
        logTable.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "LogIn", "LogOut", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(logTable);

        javax.swing.GroupLayout logPanelADLayout = new javax.swing.GroupLayout(logPanelAD);
        logPanelAD.setLayout(logPanelADLayout);
        logPanelADLayout.setHorizontalGroup(
            logPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelADLayout.createSequentialGroup()
                .addGroup(logPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logPanelADLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel6))
                    .addGroup(logPanelADLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        logPanelADLayout.setVerticalGroup(
            logPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelADLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel6)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(logPanelAD, "card3");

        jLabel4.setText("dashboard");

        javax.swing.GroupLayout dashboardPanelADLayout = new javax.swing.GroupLayout(dashboardPanelAD);
        dashboardPanelAD.setLayout(dashboardPanelADLayout);
        dashboardPanelADLayout.setHorizontalGroup(
            dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
            .addGroup(dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardPanelADLayout.createSequentialGroup()
                    .addGap(340, 340, 340)
                    .addComponent(jLabel4)
                    .addContainerGap(537, Short.MAX_VALUE)))
        );
        dashboardPanelADLayout.setVerticalGroup(
            dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(dashboardPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardPanelADLayout.createSequentialGroup()
                    .addGap(262, 262, 262)
                    .addComponent(jLabel4)
                    .addContainerGap(372, Short.MAX_VALUE)))
        );

        contentHolderAdmin.add(dashboardPanelAD, "card5");

        jLabel7.setText("product");

        javax.swing.GroupLayout productPanelADLayout = new javax.swing.GroupLayout(productPanelAD);
        productPanelAD.setLayout(productPanelADLayout);
        productPanelADLayout.setHorizontalGroup(
            productPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelADLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel7)
                .addContainerGap(619, Short.MAX_VALUE))
        );
        productPanelADLayout.setVerticalGroup(
            productPanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelADLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel7)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(productPanelAD, "card9");

        profilePanelAD.setBackground(new java.awt.Color(250, 246, 203));
        profilePanelAD.setPreferredSize(new java.awt.Dimension(1187, 600));

        Title.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 51));
        Title.setText("Manage Personal Profile");

        userTextArea.setBackground(new java.awt.Color(52, 73, 85));
        userTextArea.setColumns(20);
        userTextArea.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        userTextArea.setForeground(new java.awt.Color(255, 255, 255));
        userTextArea.setRows(5);
        userTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Name: ");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Email: ");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Contact: ");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Username: ");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        javax.swing.GroupLayout profilePanelADLayout = new javax.swing.GroupLayout(profilePanelAD);
        profilePanelAD.setLayout(profilePanelADLayout);
        profilePanelADLayout.setHorizontalGroup(
            profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelADLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(profilePanelADLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelADLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(profilePanelADLayout.createSequentialGroup()
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(53, 53, 53)
                        .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(userTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        profilePanelADLayout.setVerticalGroup(
            profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelADLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(54, 54, 54)
                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(69, 69, 69)
                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(77, 77, 77)
                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(123, 123, 123)
                .addGroup(profilePanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(profilePanelADLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(userTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentHolderAdmin.add(profilePanelAD, "card8");

        javax.swing.GroupLayout menuAdminLayout = new javax.swing.GroupLayout(menuAdmin);
        menuAdmin.setLayout(menuAdminLayout);
        menuAdminLayout.setHorizontalGroup(
            menuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAdminLayout.createSequentialGroup()
                .addComponent(naviBarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentHolderAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuAdminLayout.setVerticalGroup(
            menuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naviBarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addComponent(contentHolderAdmin)
        );

        basePanel.add(menuAdmin, "card3");

        menuPM.setBackground(new java.awt.Color(153, 153, 153));

        naviBarPM.setPreferredSize(new java.awt.Dimension(143, 522));

        profileButtonPM.setText("Manage\nPersonal\nProfile");
        profileButtonPM.setText("Manage Personal Profile");
        profileButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonPMActionPerformed(evt);
            }
        });

        catalogueButtonPM.setText("Manage Product Catalogue");
        catalogueButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogueButtonPMActionPerformed(evt);
            }
        });

        productButtonPM.setText("Manage Product Information");
        productButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonPMActionPerformed(evt);
            }
        });

        logOutPM.setText("Log Out");

        dashboardButtonPM.setText("Design Summary Dashboard");
        dashboardButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout naviBarPMLayout = new javax.swing.GroupLayout(naviBarPM);
        naviBarPM.setLayout(naviBarPMLayout);
        naviBarPMLayout.setHorizontalGroup(
            naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarPMLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(catalogueButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productButtonPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardButtonPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        naviBarPMLayout.setVerticalGroup(
            naviBarPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naviBarPMLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(profileButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(productButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(catalogueButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboardButtonPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(logOutPM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentHolderPM.setPreferredSize(new java.awt.Dimension(1187, 684));
        contentHolderPM.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout dashboardPanelPMLayout = new javax.swing.GroupLayout(dashboardPanelPM);
        dashboardPanelPM.setLayout(dashboardPanelPMLayout);
        dashboardPanelPMLayout.setHorizontalGroup(
            dashboardPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelPMLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel2)
                .addContainerGap(509, Short.MAX_VALUE))
        );
        dashboardPanelPMLayout.setVerticalGroup(
            dashboardPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelPMLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel2)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        contentHolderPM.add(dashboardPanelPM, "card5");

        jLabel3.setText("Catalogue");

        javax.swing.GroupLayout cataloguePanelPMLayout = new javax.swing.GroupLayout(cataloguePanelPM);
        cataloguePanelPM.setLayout(cataloguePanelPMLayout);
        cataloguePanelPMLayout.setHorizontalGroup(
            cataloguePanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cataloguePanelPMLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel3)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        cataloguePanelPMLayout.setVerticalGroup(
            cataloguePanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cataloguePanelPMLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel3)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        contentHolderPM.add(cataloguePanelPM, "card4");

        jLabel9.setText("Product");

        javax.swing.GroupLayout productPanelPMLayout = new javax.swing.GroupLayout(productPanelPM);
        productPanelPM.setLayout(productPanelPMLayout);
        productPanelPMLayout.setHorizontalGroup(
            productPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelPMLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productPanelPMLayout.setVerticalGroup(
            productPanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelPMLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel9)
                .addContainerGap(507, Short.MAX_VALUE))
        );

        contentHolderPM.add(productPanelPM, "card3");

        jLabel10.setText("Profile");

        javax.swing.GroupLayout profilePanelPMLayout = new javax.swing.GroupLayout(profilePanelPM);
        profilePanelPM.setLayout(profilePanelPMLayout);
        profilePanelPMLayout.setHorizontalGroup(
            profilePanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelPMLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel10)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        profilePanelPMLayout.setVerticalGroup(
            profilePanelPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelPMLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel10)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        contentHolderPM.add(profilePanelPM, "card2");

        javax.swing.GroupLayout menuPMLayout = new javax.swing.GroupLayout(menuPM);
        menuPM.setLayout(menuPMLayout);
        menuPMLayout.setHorizontalGroup(
            menuPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPMLayout.createSequentialGroup()
                .addComponent(naviBarPM, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentHolderPM, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
        );
        menuPMLayout.setVerticalGroup(
            menuPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naviBarPM, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addComponent(contentHolderPM, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        basePanel.add(menuPM, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void initPanelComponents(User user,DatabaseManager db){
        /**
         * Manage Personal Profile ADMIN
         */
        String profileInfo = "Name: \t"+user.getName() +"\n"+"Email: \t"+user.getEmail() +"\n"+"Contact: \t"+user.getContact() +"\n"+
                "Position: \t"+user.getPosition() +"\n"
                 +"Gender: \t" +user.getGender()+"\n"+ "Username: \t" + user.getLogin();
        this.userTextArea.setText(profileInfo);
        this.nameText.setText(user.getName());
        this.contactText.setText(user.getContact());
        this.emailText.setText(user.getEmail());
        this.userText.setText(user.getLogin().toString());
        System.out.println("test 4");
       
        
        
        }
        
    /**
     * Navigation Bar Switching
     * @param evt 
     */
    // <editor-fold defaultstate="collapsed" desc="Panel Switching">
    private void profileButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonADActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderAdmin,profilePanelAD );
    }//GEN-LAST:event_profileButtonADActionPerformed

    private void managerButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButtonADActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderAdmin,managerPanelAD);
    }//GEN-LAST:event_managerButtonADActionPerformed

    private void supplierButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonADActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderAdmin,supplierPanelAD);
    }//GEN-LAST:event_supplierButtonADActionPerformed

    private void productButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonADActionPerformed
         this.switchContentPanels(contentHolderAdmin,productPanelAD);
    }//GEN-LAST:event_productButtonADActionPerformed

    private void logButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonADActionPerformed
        // Inspect Log for AD
         this.switchContentPanels(contentHolderAdmin,logPanelAD);
         this.setLogTable();
    
    }//GEN-LAST:event_logButtonADActionPerformed

    private void dashboardButtonADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonADActionPerformed
        // TODO add your handling code here:
         this.switchContentPanels(contentHolderAdmin,dashboardPanelAD);
    }//GEN-LAST:event_dashboardButtonADActionPerformed

    private void profileButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonPMActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderPM, profilePanelPM);
    }//GEN-LAST:event_profileButtonPMActionPerformed

    private void productButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonPMActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderPM, productPanelPM);
    }//GEN-LAST:event_productButtonPMActionPerformed

    private void catalogueButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogueButtonPMActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderPM, cataloguePanelPM);
    }//GEN-LAST:event_catalogueButtonPMActionPerformed

    private void dashboardButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonPMActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(contentHolderPM, dashboardPanelPM);
    }//GEN-LAST:event_dashboardButtonPMActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        // TODO add your handling code here:
        this.switchContentPanels(userSubPanel, createPM);
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void viewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserButtonActionPerformed
        // View User for ADMIn
         this.switchContentPanels(userSubPanel, viewPM);
         this.setUserTable();
    }//GEN-LAST:event_viewUserButtonActionPerformed

    private void enterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButton1ActionPerformed
        // TODO add your handling code here:
        User newUser;
        LoginInfo login=null;
        if(this.checkPass()){
           String[] i = this.newUserInput();
           try{
           login = new LoginInfo(i[3],i[4]);
           }
           catch(Exception e){
               System.out.println("This is exception"+e);
           }
            System.out.println("4444");
            newUser = new ProductManager(i[0],i[1],i[2],User.Gender.MALE,login);
            System.out.println(newUser);
            System.out.println(this.model);
            try {
                this.model.DB.addUser(newUser);
            } catch (IOException ex) {
                warningLabel.setText("Registration Error");
            }
            System.out.println(this.model.DB.toString());
        }
        else{
        warningLabel.setText("Password Mismatch");
        }
    }//GEN-LAST:event_enterButton1ActionPerformed

    /*
    Logging Purposes
    */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        model.session = new Log(model.user);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        model.session.endLog();
        try{
        model.DB.addLog(model.session);
        }
        catch(Exception e){
            System.out.println("closing Logging error");
        }
        try {
            this.model.DB.serializeAll();
        } catch (IOException ex) {
            System.out.println("closing serialization error");
        }
    }//GEN-LAST:event_formWindowClosing

//</editor-fold>
    /**
     * @param args the command line arguments
     */
  

    /*
    * Menu Set up
    */
    
    
    public void setNaviBar(User.Position p) {
        basePanel.removeAll();
        switch(p){
            case ADMIN:
                basePanel.removeAll();
                basePanel.add(menuAdmin);
                basePanel.repaint();
                basePanel.revalidate();
                break;
                
            case PRODUCT_MANAGER:
                basePanel.removeAll();
                basePanel.add(menuPM);
                basePanel.repaint();
                basePanel.revalidate();
                break;
        }
    
    }
    
    
  
    /**
     * Panel Switching
     */    

    public void switchContentPanels(JLayeredPane holder, JPanel content ){
        holder.removeAll();
        holder.add(content);
        holder.repaint();
        holder.revalidate();
    }
    
    /**
     * New User
     */
    
    public String[] newUserInput(){
        String[] s= new String[5];
        s[0] = newName.getText();
        s[1] = newEmail.getText();
        s[2] = newContact.getText();
        s[3] = newUsername.getText();
        s[4] = new String(newPass1.getPassword());
        return s;
    }
  
    public boolean checkPass(){
    String s1 = new String(newPass1.getPassword());
    String s2 = new String(newPass2.getPassword());
    if (s1.equals(s2)){
        return true;
    }
    else{
        return false;
    }
    }
    
    
    /*
    Setting Tables
    */
    public void setUserTable(){
        /*
        User View
        */
        String col[] = {"Name","Contact","Email","Gender","Username"};
        DefaultTableModel tableModel = new DefaultTableModel(col,0);
        this.userTable.setModel(tableModel);
        
        TableList users = model.DB.getTable(DatabaseManager.Tables.USER);
        for (Object user1:users){
            User u = (User)user1;
            String[] obj= {u.getName(),u.getContact(),u.getEmail(),u.getGender().toString(),u.getLogin().toString()};  
            tableModel.addRow(obj);
        }
        this.userTable.setModel(tableModel);
    }
    
    public void setLogTable(){
        /*
        Log View
        */
        String col_2[] = {"User","Log In","Log Out","Duration"};
        DefaultTableModel tableModel_2 = new DefaultTableModel(col_2,0);
        this.logTable.setModel(tableModel_2);
        
        TableList logs = model.DB.getTable(DatabaseManager.Tables.LOG);
        for (Object log:logs){
            Log l = (Log)log;
            String[] obj= {l.getUser(),l.getStart(),l.getEnd(),l.getDuration()};  
            tableModel_2.addRow(obj);
        }
//        this.logTable.setModel(tableModel_2);
        
    
    }
 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewUserTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JLayeredPane basePanel;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JButton catalogueButtonPM;
    private javax.swing.JPanel cataloguePanelPM;
    private javax.swing.JTextField contactText;
    private javax.swing.JLayeredPane contentHolderAdmin;
    private javax.swing.JLayeredPane contentHolderPM;
    private javax.swing.JPanel createPM;
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton dashboardButtonAD;
    private javax.swing.JButton dashboardButtonPM;
    private javax.swing.JPanel dashboardPanelAD;
    private javax.swing.JPanel dashboardPanelPM;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton enterButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logButtonAD;
    private javax.swing.JButton logOutAD;
    private javax.swing.JButton logOutPM;
    private javax.swing.JPanel logPanelAD;
    private javax.swing.JTable logTable;
    private javax.swing.JButton managerButtonAD;
    private javax.swing.JPanel managerPanelAD;
    private javax.swing.JPanel menuAdmin;
    private javax.swing.JPanel menuPM;
    private javax.swing.JTextField nameText;
    private javax.swing.JPanel naviBarAdmin;
    private javax.swing.JPanel naviBarPM;
    private javax.swing.JTextField newContact;
    private javax.swing.JTextField newEmail;
    private javax.swing.JTextField newName;
    private javax.swing.JPasswordField newPass1;
    private javax.swing.JPasswordField newPass2;
    private javax.swing.JTextField newUsername;
    private javax.swing.JButton productButtonAD;
    private javax.swing.JButton productButtonPM;
    private javax.swing.JPanel productPanelAD;
    private javax.swing.JPanel productPanelPM;
    private javax.swing.JButton profileButtonAD;
    private javax.swing.JButton profileButtonPM;
    private javax.swing.JPanel profilePanelAD;
    private javax.swing.JPanel profilePanelPM;
    private javax.swing.JButton supplierButtonAD;
    private javax.swing.JPanel supplierPanelAD;
    private javax.swing.JButton updateButton;
    private javax.swing.JLayeredPane userSubPanel;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField userText;
    private javax.swing.JTextArea userTextArea;
    private javax.swing.JPanel viewPM;
    private javax.swing.JButton viewUserButton;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables


}
